version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:5000"
    networks:
      - app-network


  postgres:
    image: postgres:15
    container_name: reciplanner-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reciplanner
    ports:
      - "5434:5432"
    networks:
      - app-network      

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
